spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        javax:
          persistence:
            validation:
              mode: none
  jackson:
      serialization:
        write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    tomcat:
      maxActive: 10
      minIdle: 1
      initialSize: 1